language: android

dist : trusty

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-27.0.1
    - android-27

before_install:
    - yes | sdkmanager "build-tools;28.0.3"
    - yes | sdkmanager "platforms;android-29"
    - touch $HOME/.android/repositories.cfg

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew
  
script:
  ./gradlew build
